# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Kong CI Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN: true
    steps:
    - uses: actions/checkout@v4
  
    - name: Install Compose
      uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.14.2' # the full version of `docker-compose` command
  
    - run: docker-compose --version

    - name: Start kong services
      run: docker-compose up -d


    - name: Install Cypress
      run: |
        export DEBIAN_FRONTEND=noninteractive
        uname -a
        sudo apt update
        sudo apt-get install --yes libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
        sudo apt install --yes nodejs
        node -v
        npm install cypress --save-dev
        npm install mocha-junit-reporter --save-dev
        npm install ts-node --save-dev
        npm install eslint-plugin-cypress --save-dev
        npm install --save-dev allure-commandline
        npm install --save-dev allure-cypress
        npm list
        
    - name: Run Cypress Tests
      run: |
        npx cypress run --env allure=true
    # - name: Publish Test Results
    #   uses: EnricoMi/publish-unit-test-result-action@v2
    #   if: always()
    #   with:
    #     files: |
    #       test-results/**/*.xml
    #       test-results/**/*.trx
    #       test-results/**/*.json


    - name: Upload allure results to artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          allure-results

    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: allure-results
        
    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
